theme: jekyll-theme-minimal
<!DOCTYPE html>
<html lang="en">
  <head>
  
    <!-- Testimonials Section
    ==========================================-->
    <div id="tf-testimonials" class="text-center">
        <div class="overlay">
            <div class="container">
                <div class="section-title center">
                    <h2><strong>我的</strong> 实验</h2>
 <div class="space"></div>
            <div class="row">
                <div class="col-md-3 col-sm-6 service">
                    <h4><strong>实验一</strong></h4>
                    <ul>
              
                        <li><p><a href="../实验一/实验一.html" target="_blank">sy1-1</a></p></li>
                        <li><p><a href= "../实验一/实验二.html" target="_blank">sy1-2</a></p></li>
                        <li><p><a href="../实验一/实验三.html" target="_blank">sy1-3</a></p></li>
                        <li><p><a href="../实验一/实验四.html" target="_blank">sy1-4</a></p></li>
                        <li><p><a href="../实验一/实验五.html" target="_blank">sy1-5</a></p></li>
						<li><p><a href="../实验一/实验六.html" target="_blank">sy1-6</a></p></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 service">
                    <h4><strong>实验二</strong></h4>
                    <ul>
                        <li><p><a href="../实验二/实验一.html" target="_blank">sy2-1</a></p></li>
                        <li><p><a href="../实验二/实验二.html" target="_blank">sy2-2</a></p></li>
                        <li><p><a href="../实验二/实验三.html" target="_blank">sy2-3</a></p></li>
                        <li><p><a href="../实验二/实验四.html" target="_blank">sy2-4</a></p></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 service">
                    <h4><strong>实验三</strong></h4>
                    <ul>
                        <li><p><a href="../实验三/实验一.html" target="_blank">sy3-1</a></p></li>
                        <li><p><a href="../实验三/实验二.html" target="_blank">sy3-2</a></p></li>
                        <li><p><a href="../实验三/实验三.html" target="_blank">sy3-3</a></p></li>
                        <li><p><a href="../实验三/实验四.html" target="_blank">sy3-4</a></p></li>
                        <li><p><a href="../实验三/实验五.html" target="_blank">sy3-5</a></p></li>
                        <li><p><a href="../实验三/实验六.html" target="_blank">sy3-6</a></p></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 service">
                    <h4><strong>实验四</strong></h4>
                    <ul>
                        <li><p><a href="../实验四/实验一.html" target="_blank">sy4-1</a></p></li>
                        <li><p><a href="../实验四/实验二.html" target="_blank">sy4-2</a></p></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 col-sm-6 service">
                    <h4><strong>实验五</strong></h4>
                    <ul>
                        <li><p><a href="../实验五/实验一.html" target="_blank">sy5</a></p></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 service">
                    <h4><strong>实验六</strong></h4>
                    <ul>
                        <li><p><a href="../实验六/实验一.html" target="_blank">sy6</a></p></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 service">
                    <h4><strong>实验七</strong></h4>
                    <ul>
                        <li><p><a href="../实验七/实验一.html" target="_blank">sy7-1</a></p></li>
                        <li><p><a href="../实验七/实验二.html" target="_blank">sy7-2</a></p></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 service">
                    <h4><strong>实验八</strong></h4>
                    <ul>
                        <li><p><a href="index.html" target="_blank">sy8</a></p></li>
                    </ul>
                </div>
            </div>
				</div>
            </div>
        </div>
    </div>

    <!-- Contact Section
    ==========================================-->
    <div id="tf-contact" class="text-center">
        <div class="container">

            <div class="row">
                <div class="col-md-8 col-md-offset-2">

                    <div class="section-title center">
                        <h2>随时与我<strong>联系</strong></h2>
                        <div class="line">
                            <hr>
                        </div>
                                   
                    </div>

                    <form>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">电子邮箱</label>
                                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="电子邮箱">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputPassword1">密码</label>
                                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="密码">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">反馈</label>
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        
                        <button type="submit" class="btn tf-btn btn-default">提交</button>
                    </form>

                </div>
            </div>

        </div>
    </div>

    <nav id="footer">
        <div class="container">
            <div class="pull-left fnav">
              
            </div>
            <div class="pull-right fnav">
                <ul class="footer-social">
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                </ul>
            </div>
        </div>
    </nav>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript" src="js/jquery.1.11.1.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script type="text/javascript" src="js/bootstrap.js"></script>
    <script type="text/javascript" src="js/SmoothScroll.js"></script>
    <script type="text/javascript" src="js/jquery.isotope.js"></script>

    <script src="js/owl.carousel.js"></script>

    <!-- Javascripts
    ================================================== -->
    <script type="text/javascript" src="js/main.js"></script>

  </body>
</html>
